name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
          # This line tells the bot to find and update the version field in your manifest
          extra-files: |
            {"type":"json","path":"manifest.json","jsonpath":"$.version"}
